"""에러 코드 사전. EduTrust DB 설계서 7장 CHECK 권장값을 그대로 상수화."""

from enum import StrEnum


class AuthError(StrEnum):
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_MISSING = "TOKEN_MISSING"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_WRONG_TYPE = "TOKEN_WRONG_TYPE"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    OTP_NOT_FOUND = "OTP_NOT_FOUND"
    OTP_EXPIRED = "OTP_EXPIRED"
    OTP_MISMATCH = "OTP_MISMATCH"
    OTP_MAX_ATTEMPTS = "OTP_MAX_ATTEMPTS"
    OTP_ALREADY_CONSUMED = "OTP_ALREADY_CONSUMED"
    PHONE_NOT_VERIFIED = "PHONE_NOT_VERIFIED"
    KIOSK_KEY_INVALID = "KIOSK_KEY_INVALID"
    KIOSK_INACTIVE = "KIOSK_INACTIVE"


class AdultVerificationStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAIL_AGE = "FAIL_AGE"
    FAIL_FACE_MISMATCH = "FAIL_FACE_MISMATCH"
    FAIL_LIVENESS = "FAIL_LIVENESS"
    ERROR = "ERROR"


class VerificationResultStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAIL_EXPIRED = "FAIL_EXPIRED"
    FAIL_FACE_MISMATCH = "FAIL_FACE_MISMATCH"
    FAIL_INVALID_VC = "FAIL_INVALID_VC"
    FAIL_INVALID_VP = "FAIL_INVALID_VP"
    FAIL_REVOKED_VC = "FAIL_REVOKED_VC"
    FAIL_CHALLENGE = "FAIL_CHALLENGE"
    INTERNAL_ERROR = "INTERNAL_ERROR"