"""create initial schema

Revision ID: 69dc2d9f707c
Revises: 
Create Date: 2026-08-10 08:13:52.238821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69dc2d9f707c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_number', sa.String(length=50), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('contact_number', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'TERMINATED')", name='ck_businesses_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_number')
    )
    op.create_table('credential_status_lists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('issuer_did', sa.String(length=500), nullable=False),
    sa.Column('status_purpose', sa.String(length=30), nullable=False),
    sa.Column('status_list_url', sa.Text(), nullable=False),
    sa.Column('encoded_list', sa.Text(), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status_purpose IN ('REVOCATION', 'SUSPENSION')", name='ck_credential_status_lists_status_purpose'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_list_url')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('phone_verification_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('otp_digest', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=30), server_default='SIGN_UP', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resend_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_sent_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_phone_verification_requests_lookup', 'phone_verification_requests', ['phone_number', 'purpose', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('phone_verified_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('platform_role', sa.String(length=30), server_default='USER', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawn_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("platform_role IN ('USER', 'ADMIN')", name='ck_users_platform_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('business_memberships',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('business_role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("business_role IN ('OWNER', 'MANAGER', 'STAFF')", name='ck_business_memberships_business_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_business_memberships_status'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'business_id', name='uq_business_memberships_user_business')
    )
    op.create_table('devices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_identifier', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('holder_did', sa.String(length=500), nullable=True),
    sa.Column('holder_public_key', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("platform IN ('ANDROID', 'IOS')", name='ck_devices_platform'),
    sa.CheckConstraint("status IN ('ACTIVE', 'REVOKED', 'LOST')", name='ck_devices_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_identifier'),
    sa.UniqueConstraint('holder_did')
    )
    op.create_table('stores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('store_code', sa.String(length=100), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('store_type_code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('contact_number', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'TERMINATED')", name='ck_stores_status'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_code')
    )
    op.create_table('user_consents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('consent_type', sa.String(length=30), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('agreed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawn_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("consent_type IN ('TERMS', 'PRIVACY', 'BIOMETRIC')", name='ck_user_consents_consent_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adult_verifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('age_check_passed', sa.Boolean(), nullable=False),
    sa.Column('id_face_match_passed', sa.Boolean(), nullable=False),
    sa.Column('liveness_passed', sa.Boolean(), nullable=True),
    sa.Column('age_policy_version', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('threshold_version', sa.String(length=100), nullable=True),
    sa.Column('result_status', sa.String(length=50), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invalidated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("result_status IN ('SUCCESS', 'FAIL_AGE', 'FAIL_FACE_MISMATCH', 'FAIL_LIVENESS', 'ERROR')", name='ck_adult_verifications_result_status'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kiosks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('kiosk_identifier', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('software_version', sa.String(length=100), nullable=True),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE', 'REVOKED')", name='ck_kiosks_status'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kiosk_identifier')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('actor_ref', sa.String(length=255), nullable=True),
    sa.Column('source_kiosk_id', sa.BigInteger(), nullable=True),
    sa.Column('aggregate_type', sa.String(length=100), nullable=True),
    sa.Column('aggregate_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kafka_topic', sa.String(length=255), nullable=True),
    sa.Column('kafka_partition', sa.Integer(), nullable=True),
    sa.Column('kafka_offset', sa.BigInteger(), nullable=True),
    sa.Column('previous_hash', sa.String(length=128), nullable=True),
    sa.Column('event_hash', sa.String(length=128), nullable=False),
    sa.Column('archive_object_key', sa.String(length=1000), nullable=True),
    sa.Column('archive_object_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('USER', 'ADMIN', 'KIOSK', 'SYSTEM')", name='ck_audit_logs_actor_type'),
    sa.ForeignKeyConstraint(['source_kiosk_id'], ['kiosks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('kafka_topic', 'kafka_partition', 'kafka_offset', name='uq_audit_logs_kafka_position')
    )
    op.create_table('vc_credentials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('adult_verification_id', sa.BigInteger(), nullable=False),
    sa.Column('credential_id', sa.String(length=500), nullable=False),
    sa.Column('holder_did', sa.String(length=500), nullable=False),
    sa.Column('issuer_did', sa.String(length=500), nullable=False),
    sa.Column('credential_type', sa.String(length=100), server_default='AdultCredential', nullable=False),
    sa.Column('credential_format', sa.String(length=50), nullable=True),
    sa.Column('credential_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('status_list_id', sa.BigInteger(), nullable=True),
    sa.Column('status_list_index', sa.BigInteger(), nullable=True),
    sa.Column('issued_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'REVOKED', 'EXPIRED')", name='ck_vc_credentials_status'),
    sa.ForeignKeyConstraint(['adult_verification_id'], ['adult_verifications.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['status_list_id'], ['credential_status_lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id'),
    sa.UniqueConstraint('status_list_id', 'status_list_index', name='uq_vc_credentials_status_list_position')
    )
    op.create_table('verification_challenges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kiosk_id', sa.BigInteger(), nullable=False),
    sa.Column('transport_type', sa.String(length=20), nullable=False),
    sa.Column('challenge_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'CONSUMED', 'EXPIRED', 'CANCELLED')", name='ck_verification_challenges_status'),
    sa.CheckConstraint("transport_type IN ('QR', 'NFC', 'BLE')", name='ck_verification_challenges_transport_type'),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_hash')
    )
    op.create_table('verification_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('is_vc_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_vp_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_face_matched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_liveness_valid', sa.Boolean(), nullable=True),
    sa.Column('face_model_version', sa.String(length=100), nullable=True),
    sa.Column('threshold_version', sa.String(length=100), nullable=True),
    sa.Column('result_status', sa.String(length=50), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result_status IN ('SUCCESS', 'FAIL_EXPIRED', 'FAIL_FACE_MISMATCH', 'FAIL_INVALID_VC', 'FAIL_INVALID_VP', 'FAIL_REVOKED_VC', 'FAIL_CHALLENGE', 'INTERNAL_ERROR')", name='ck_verification_logs_result_status'),
    sa.ForeignKeyConstraint(['challenge_id'], ['verification_challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_logs')
    op.drop_table('verification_challenges')
    op.drop_table('vc_credentials')
    op.drop_table('audit_logs')
    op.drop_table('kiosks')
    op.drop_table('adult_verifications')
    op.drop_table('user_consents')
    op.drop_table('stores')
    op.drop_table('devices')
    op.drop_table('business_memberships')
    op.drop_table('users')
    op.drop_index('ix_phone_verification_requests_lookup', table_name='phone_verification_requests')
    op.drop_table('phone_verification_requests')
    op.drop_table('outbox_events')
    op.drop_table('credential_status_lists')
    op.drop_table('businesses')
    # ### end Alembic commands ###
